{   'active': False,
    'author': 'No author.',
    'category': 'base.module_category_hidden',
    'data': [   u'security/procurement_materials_group.xml',
                u'view/request_line_view.xml',
                u'view/request_view.xml',
                u'data/request_line_properties.xml',
                u'data/request_properties.xml',
                u'data/request_line_track.xml',
                u'data/request_track.xml',
                u'workflow/request_workflow.xml',
                'security/ir.model.access.csv',
                u'view/procurement_materials_menuitem.xml',
                u'view/procurement_materials_actions.xml'],
    'depends': [u'product', u'crm'],
    'description': 'No documented',
    'installable': True,
    'license': 'AGPL-3',
    'name': 'procurement_materials',
    'test': [],
    'version': 'No version',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
